### ISSUE TITLE
Calendar Window mis aligned when date input is in corner

### ISSUE THREAD

**Issue by manhar-developer** [evansmwendwa/ng2-daterangepicker#105]
When the date input is in extreme corner , the calendar pop over is mis aligned and display vertically. It should show both start and end calendar horizontally. 
![daterange](https://user-images.githubusercontent.com/32042376/43752746-0dcc935c-9a20-11e8-98ef-f618f83d0a3e.JPG)

**Comment by evansmwendwa** [comment]
It displays in verticle when there's not enough space. Check the constraints of the container element
