### ISSUE TITLE
cannot set default ranges(Angular4)

### ISSUE THREAD

**Issue by loveabc** [evansmwendwa/ng2-daterangepicker#107]
My app has 3 ranges,last 2 days, last 7 days, last 30 days.However no matter how i set default ,drop down shows last 2 days.
Such as ,today is 2018-08-23, i set begin date  to be 2018-08-17, end date to be 2018-08-23(last 7 days),when i open drop down, default range is last 2 days still.How can i do?
Thanks

**Comment by monalipatwa** [comment]
I am facing same issue, how you resolved this problem
