### ISSUE TITLE
(selected) event is not called on second attempt of same day.

### ISSUE THREAD

**Issue by mherried** [evansmwendwa/ng2-daterangepicker#109]
Reproduction steps.

Select the datepicker for todays date.
Clear the selection (Backspace)
Select the datepicker again for todays date.   This will not call the event 
(selected)="selectedDueDate($event)" 

public optionsSingle: any = {
        autoUpdateInput: false,
        showDropdowns: true,
        locale: { format: 'MM/DD/YYYY' },
        alwaysShowCalendars: true,
        singleDatePicker: true,
        minDate: '01/01/0001',
    };

**Comment by evansmwendwa** [comment]
can you provide a sample code on codesandbox or an online editor we have a look at it?

**Comment by mherried** [comment]
Attached example code of component.
[edit-tasks.component.zip](https://github.com/evansmwendwa/ng2-daterangepicker/files/2350263/edit-tasks.component.zip)

**Comment by mherried** [comment]
See attached above, please let me know if I can provide anything else.

**Comment by evansmwendwa** [comment]
Closed due to inactivity
