### ISSUE TITLE
callback function inject

### ISSUE THREAD

**Issue by ryoostar** [evansmwendwa/ng2-daterangepicker#11]
hi. how to get range label when apply date. maybe your @Output selected function hasn't third parameter 'label'. please fix it or reply~

Code from http://www.daterangepicker.com/#usage 

```
`$('input[name="daterange"]').daterangepicker(
{
    locale: {
      format: 'YYYY-MM-DD'
    },
    startDate: '2013-01-01',
    endDate: '2013-12-31'
}, 
function(start, end, label) {
    alert("A new date range was chosen: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
});`
```

**Comment by evansmwendwa** [comment]
Looking into it. Will update soon

**Comment by evansmwendwa** [comment]
Update to version v2.0.6 - you should be able to get the label together with the daterange. See README.md for an example

**Comment by ryoostar** [comment]
@evansmwendwa thanks~
