### ISSUE TITLE
Can't use singleton of DaterangepickerConfig for a modular project

### ISSUE THREAD

**Issue by SlidEnergy** [evansmwendwa/ng2-daterangepicker#112]
I have Core, Shared and lazy loading Future modules. For import daterangepicker directive to Future modules I export daterangepicker in Shared module and then import Shared module in Future.
But for each Future module I have instanse of DateRangepickerConfig and I need global configure daterangepicker in each module.
I want configure daterangepicker global one time in my Core module. Core module is place for all singleton services. 
For that I suppose to need call a forRoot method ([forRoot() and forChild()
](https://angular.io/guide/lazy-loading-ngmodules#forroot-and-forchild)) in Core module (imports section) and export daterangepicker in Shared module as before.

**Comment by evansmwendwa** [comment]
Closed due to inactivity
