### ISSUE TITLE
Change daterangepicker settings dynamically

### ISSUE THREAD

**Issue by ghost** [evansmwendwa/ng2-daterangepicker#114]
I am using ng2-daterangepicker in my angular 6 application. On constructor when i am initialising for the first time it works fine as expected. Below is my code.
constructor(private daterangepickerOptions: DaterangepickerConfig) {
    // setup data range picker initial date
    this.daterange.start = moment().subtract(1, 'days');
    this.daterange.end = moment();

    var startText = this.daterange.start.format('DD MMMM, YYYY HH:mm').toString();
    var endText = this.daterange.end.format('DD MMMM, YYYY HH:mm').toString();
    var rangeText = startText + " - " + endText;
    this.dateRangeText = rangeText;

    console.log(this.dateRangeText);

    this.daterangepickerOptions.settings = {
      locale: { format: 'DD/MM/YYYY' },
      alwaysShowCalendars: false,
      ranges: {
        'Last 15 minutes': [moment().subtract(15, 'minute'), moment()],
        'Last 30 minutes': [moment().subtract(30, 'minute'), moment()],
        'Last 1 hour': [moment().subtract(1, 'hour'), moment()],
        'Yesterday': [moment().subtract(1, 'day'), moment()],
        'Last week': [moment().subtract(1, 'week'), moment()],
        'Last Month': [moment().subtract(1, 'month'), moment()],
        'Last 3 Months': [moment().subtract(4, 'month'), moment()],
        'Last 6 Months': [moment().subtract(6, 'month'), moment()],
        'Last 12 Months': [moment().subtract(12, 'month'), moment()],
      },
      timePicker: true,
      timePicker24Hour: true,
      linkedCalendars: true,
      autoUpdateInput: true,
      cancelClass: "cancelClass",
      opens: 'right',
      maxDate: moment()
    };
  }

HTML

![image](https://user-images.githubusercontent.com/25897636/48121125-1c27a000-e29a-11e8-9f9c-d2e719442657.png)

But when i am clicking on the range line last 15 minutes then always it is taking the time range when the page is loaded for the first time instead of taking the current latest time. So i tried to initialize the component again on the showDaterangepicker method and it will get fired when ever i will click on the calendar and now i am able to see the latest time in the calendar. 

But the issue is if i am including the settings to have the ranges and time options the calender is not opening for me, the event is getting fired though. 
Below is my code in the showDaterangepicker method .

public calendarEventsHandler(e: any) {
    console.log(e,"called my calender");
    //this.loadcalender();

    console.log("i am loading again")
    // setup data range picker initial date
    this.daterange.start = moment().subtract(1, 'days');
    this.daterange.end = moment();

    var startText = this.daterange.start.format('DD MMMM, YYYY HH:mm').toString();
    var endText = this.daterange.end.format('DD MMMM, YYYY HH:mm').toString();
    var rangeText = startText + " - " + endText;
    this.dateRangeText = rangeText;

    console.log(this.dateRangeText);
    // this.daterangepickerOptions.settings={};
    this.daterangepickerOptions.settings = {
      locale: { format: 'DD/MM/YYYY' },
      alwaysShowCalendars: false,
      ranges: {
        'Last 15 minutes': [moment().subtract(15, 'minute'), moment()],
        'Last 30 minutes': [moment().subtract(30, 'minute'), moment()],
        'Last 1 hour': [moment().subtract(1, 'hour'), moment()],
        'Yesterday': [moment().subtract(1, 'day'), moment()],
        'Last week': [moment().subtract(1, 'week'), moment()],
        'Last Month': [moment().subtract(1, 'month'), moment()],
        'Last 3 Months': [moment().subtract(4, 'month'), moment()],
        'Last 6 Months': [moment().subtract(6, 'month'), moment()],
        'Last 12 Months': [moment().subtract(12, 'month'), moment()],
      },
      timePicker: true,
      timePicker24Hour: true,
      linkedCalendars: true,
      autoUpdateInput: true,
      cancelClass: "cancelClass",
      opens: 'right',
      maxDate: moment()
    };

How i can get the thing work ?

**Comment by HackPoint** [comment]
@Abhipattanayak do you know how to manualy open a datepicker or how to make it single for multiple inputs?
The owner of this component do not provide much info

**Comment by evansmwendwa** [comment]
Closed due to inactivity
