### ISSUE TITLE
minYear and maxYear not applied

### ISSUE THREAD

**Issue by igortas** [evansmwendwa/ng2-daterangepicker#115]
Hi,

When I try to set min and max year in the options object those properties are not applied, showDropdowns is set to true and dropdowns are visible, but years min and max are not updated properly.

  public options: any = {
    locale: { format: 'YYYY-MM-DD' },
    alwaysShowCalendars: false,
    showDropdowns: true,
    minYear: 1901,
    maxYear: 1910,
  }

BR,

**Comment by aks1994** [comment]
Is there any way to make minYear and maxYear work with this library?

@igortas were you able to find a workaround?

**Comment by igortas** [comment]
I think yes, but I can't remember well...
This is what I found in my pc, it's angular implementation:

`
this.daterangepickerOptions.skipCSS = true; 
`

`

    this.daterangepickerOptions.settings = {
      locale: { format: this.dateFormat },
      alwaysShowCalendars: false,
      autoApply: true,
      singleDatePicker: this.singleDatePicker,
      minDate: moment(),
      maxDate: moment().add('2', 'years'),
      maxSpan: { days: 7 }
    } }
`

**Comment by aks1994** [comment]
Thanks for the info, but guess you did not end up using maxYear and minYear.

The other options seem to work, but bit strange that maxYear and minYear are not working for the dropdowns in this angular library. The example from the original jquery library works fine.

**Comment by evansmwendwa** [comment]
Doesn't mindate and maxdate achieve the same?

**Comment by aks1994** [comment]
@evansmwendwa No, minYear and maxYear control the list of years that appear in the dropdowns in the calendar. minDate and maxDate control the min and max dates allowed in the control

If you see the attached screenshots, when showDropdowns=true, the minYear and maxYear of 2011 and 2014 change the options in the dropdown

<img width="311" alt="Screenshot 2019-09-21 at 1 36 06 PM" src="https://user-images.githubusercontent.com/30187636/65370293-c7ec9b00-dc74-11e9-8c14-0cbc0d09ec51.png">
<img width="330" alt="Screenshot 2019-09-21 at 1 35 57 PM" src="https://user-images.githubusercontent.com/30187636/65370294-c9b65e80-dc74-11e9-84d2-61216ec98e8c.png">

**Comment by evansmwendwa** [comment]
You can pass any required options in the `options` property

**Comment by aks1994** [comment]
@evansmwendwa I am passing min year and max year in options but they are not being read from there in this library. Please check

**Comment by evansmwendwa** [comment]
![Annotation 2020-02-28 075950](https://user-images.githubusercontent.com/3830832/75511820-6fc67b80-5a00-11ea-9fb8-ff8b1d57bc34.png)

Try using the latest version and pass min and max year in options

```
minYear: 2000,
maxYear: 2005,
```
