### ISSUE TITLE
Custom date-range picker is not working in iOS

### ISSUE THREAD

**Issue by ishandeb** [evansmwendwa/ng2-daterangepicker#120]
Hi,
I am using ng2-daterange picker in my Angular 5+ Application to build Android and iOS App.
But after building the custom date-rage picker is not working in iOS App.
So how to solve this problem? I am stuck with this problem. Please give any solution.

**Comment by evansmwendwa** [comment]
IOS is completely out of scope for this package. If it works on chrome I leave the rest to the implementer to fix
