### ISSUE TITLE
Setting Time Using setStartDate/setEndDate

### ISSUE THREAD

**Issue by sameer-ah** [evansmwendwa/ng2-daterangepicker#123]
Hello,
When date is changed using setStartDate/setEndDate, time drop-downs (hours/minutes/seconds) do not reflect the change. 
While investigating further into the issue, it turned out this was a bug in bootstrap-daterangepicker which was fixed in version 3.0.4. Since, ng2-daterangepicker is still using version 2.1.30 of bootstrap-daterangepicker, the issue is still there when using ng2-daterangepicker.
Is there any plan to switch to latest version of bootstrap-daterangepicker? It will help resolve the above issue and may be some others as well.
Thanks.

**Comment by sameer-ah** [comment]
@evansmwendwa , is this issue fixed?

**Comment by evansmwendwa** [comment]
Kindly test with the new version. If still broken we can reopen
