### ISSUE TITLE
maxSpan format of passed object

### ISSUE THREAD

**Issue by LosDavidos** [evansmwendwa/ng2-daterangepicker#124]
Hello.
According to daterangepicker.com documentation I tried to use option maxSpan by passing exampled object generated by 'Configuration Generator'.

My options are:

> this.options = {
>       locale: {
>         format: 'DD.MM.YYYY',
>         firstDay: 1
>       },
>       showDropdowns: true,
>       showCustomRangeLabel: true,
>       autoApply: true,
>       maxSpan: { days: 7 },
>     };

Unfortunately maxSpan option doesn't affect on calendar. I can select whatever I want instead of 7 days only.
What should I pass as maxSpan object?

**Comment by sameer-ah** [comment]
Hello @LosDavidos ,
Please use property name '**dateLimit**'. daterangepicker.com documentation is for the recent version of daterangepicker but ng2-daterangepicker is still using an older version which has property name 'dateLimit'. 
The object you are passing i.e. { days: 7} is correct.

**Comment by LosDavidos** [comment]
Works perfect. Thx!
