### ISSUE TITLE
endDate is always resetting, when selecting startDate in custom date range.

### ISSUE THREAD

**Issue by AmitChandra** [evansmwendwa/ng2-daterangepicker#125]
I am using custom date range option. The scenario is below:
1. I am selecting the startDate and endDate from custom date range and applying the changes, it's working fine(for the very first time).
2. When i am repeating the same step from second time on wards i found that whenever, i am selecting the startDate, it's resetting the endDate always, even though i have endDate value.

My question :
Is there a way, so that, if i will select the startDate the endDate should not be reset automatically, or if there is a value for endDate it should not reset itSelf?

**Comment by evansmwendwa** [comment]
Kindly test with the latest version

**Comment by evansmwendwa** [comment]
selecting a range always starts with start date then end date. You can't select the range backwards
