### ISSUE TITLE
Way for InlineMode?

### ISSUE THREAD

**Issue by MisterEd0105** [evansmwendwa/ng2-daterangepicker#13]
Hey,

is there a way to use this picker in inline-mode?
- no popup
- no inputField

just the pure picker...

**Comment by evansmwendwa** [comment]
I haven't seen such possibility yet. 
You can have a look at the features available in the original datepicker http://www.daterangepicker.com/ and see if you are able to customize it.

This project only ports the original  Bootstrap Daterangepicker so it can be used in Angular 2+ typescript projects and provides no extra features.
