### ISSUE TITLE
not working on my angular9 project

### ISSUE THREAD

**Issue by ahtesham-clcbws** [evansmwendwa/ng2-daterangepicker#131]
i already install types/jquery, jquery, jquery-migrate and momentjs

some plugins need migrate so i installed it, it also showa migrate message in console, that means jquery works fine, i dont know but datepicker not works, no errors even shows in console

**Comment by evansmwendwa** [comment]
Share sample of your code

**Comment by ahtesham-clcbws** [comment]
https://github.com/ahtesham-clcbws/bookingsystem

here is my repo brother, i updated all code here, using app.module for imports, then put in src/app/public/homepage component. please look into it if possible,

**Comment by ahtesham-clcbws** [comment]
going to use another datepicker
