### ISSUE TITLE
DaterangePickerComponent is undefined

### ISSUE THREAD

**Issue by idrakimuhamad** [evansmwendwa/ng2-daterangepicker#15]
I'm trying out the new picker methods, by following the sample from the doc.

https://github.com/evansmwendwa/ng2-daterangepicker#daterangepicker-methods

But I'm getting undefined from `picker` whenever I tried to use the method. I'm following the sample code given, except that my HTML is like below.

```
<div
    class="input-other-date-picker"
    daterangepicker
    [options]="dateOptions">
      From {{ selectedDate.start | date:'dd-MM-yyyy'}} to {{ selectedDate.end | date:'dd-MM-yyyy'}}
</div>
```

And the date option. The datepicker came out just fine, but I'm trying to reset the value of start date and end date when the user are done.

```
dateOptions: any = {
    locale: { format: 'DD-MM-YYYY' },
    startDate: this.selectedDate.start,
    endDate: this.selectedDate.end
  };
```

I've altered your plunk and put a button that should trigger the method and you can see the console to see the thrown error. https://embed.plnkr.co/hPpq8zrWxP4i5ORcv2CC/

If I'm implementing it the wrong way, please do let me know.

**Comment by idrakimuhamad** [comment]
Hey thanks. I've update the plunker to implement your suggestion, but it still throwing undefined.

`Cannot read property 'setStartDate' of undefined`

**Comment by evansmwendwa** [comment]
In your plunker code you are using a lower version of ng2-daterangepicker. Update the version to v2.0.6.

Here is a working plunker example https://embed.plnkr.co/iAKWCHDFJgl8rQ2lmyyg/

**Comment by idrakimuhamad** [comment]
Thanks Evan.

Its working as expected in the Plunkr, however, my project still getting `undefined`. Must be something within my app, so I'll dissect my codebase to find the problem. Thanks!

**Comment by bputt** [comment]
@idrakimuhamad did you ever figure out what the issue was within your app for the ```Cannot read property 'setStartDate' of undefined``` issue?

**Comment by evansmwendwa** [comment]
@bputt do you have any sample code? I can try to assist you

**Comment by bputt** [comment]
@evansmwendwa I believe it's a timing issue related to https://github.com/angular/angular/issues/17473#issuecomment-327766638 as changing it to ngAfterViewInit works fine
