### ISSUE TITLE
Can we Modify Starts year in single date picker. 

### ISSUE THREAD

**Issue by nishant0131** [evansmwendwa/ng2-daterangepicker#19]
I want to set the custom start year in the single datepicker. How can i do this. Is there any option for customization. 

Thanks for great library for datepicker.

**Comment by evansmwendwa** [comment]
You can set both `startDate` and `endDate` to the same date (full date format not just year)

``` javascript
startDate: '01/01/2017', endDate: '01/01/2017' 
```
