### ISSUE TITLE
'oncancel' not working

### ISSUE THREAD

**Issue by priyaponni** [evansmwendwa/ng2-daterangepicker#2]
Hi,

I am trying to execute the oncancel.daterangepicker hook from my component. Tried it in the ngAfterViewInit using @ViewChild element. 

 ` $(this.el.nativeElement).on('cancel.daterangepicker', function(ev, picker) {
        console.log('clear called');
      });`.

I was able to add the 'clear' button, but the hook is not executing. Can you please help on how I can get there? 

Thanks.

**Comment by evansmwendwa** [comment]
We have added support for events using the Angular EventEmitter so now you should be able to use the events in your component. See the documentation for more detailed usage example. https://github.com/evansmwendwa/ng2-daterangepicker#using-daterangepicker-events

Don't forget to update to the latest version 1.1.0
