### ISSUE TITLE
Build size has doubled 

### ISSUE THREAD

**Issue by steelx** [evansmwendwa/ng2-daterangepicker#22]
Thanks for creating this component.

But before using this module my build size was **430KB**, and now with ng2-daterangepicker module file size has doubled.
**vendor.f0f9d51956634897db29.bundle.js	200	script	home	859 KB**

Please revert.

**Comment by evansmwendwa** [comment]
The documentation clear say the module is a port of a jQuery plugin that uses Bootstrap. If you are not already using jQuery and Bootstrap in your project then I recommend using another module. This module is targeted for use in large projects that are already using jQuery and Bootstrap for other things
