### ISSUE TITLE
Opening DateRangePicker outside component

### ISSUE THREAD

**Issue by aribhatt** [evansmwendwa/ng2-daterangepicker#24]
I am trying to open date range picker from a modal component. But Its opening the calendars outside the modal (in the background) and when using custom style instead of bootstrap.css its not opening at all.

Further, on starting the application a small dialogbox with apply/cancel buttons and the date range inputs are visible. I want it to be visible only after I call for it.

**Comment by evansmwendwa** [comment]
Can you provide a plunker sample of your code or a link to a git repo? I'ts a bit difficult to assist you without a look at your usage scenario.

Is your modal component using the bootstrap modal component or a custom one?
