### ISSUE TITLE
Issue with multiple components

### ISSUE THREAD

**Issue by BenevidesLecontes** [evansmwendwa/ng2-daterangepicker#25]
Hi @evansmwendwa, thanks for your amazing work. I did an component, using daterangepicker. it seems that if i multiple instances of my component, all the instances are being setup with the same config, even if i pass different inputs for each one. Take a look at my gist.
https://gist.github.com/BenevidesLecontes/7f828eef7a4e6a7aee8b0253079aba6b

**Comment by evansmwendwa** [comment]
The picker is initialized using the options object passed and not the bound input, the bound input has to be manually updated every time the picker changes.

If you share a gist to your template `ui-kit.components/ui-date-rangepicker/ui-date-rangepicker.component.html` I can try and reproduce the issue.

**Comment by BenevidesLecontes** [comment]
@evansmwendwa here's my template https://gist.github.com/BenevidesLecontes/10f2dc4f8b492e4480b9be0d29f4d7eb

**Comment by evansmwendwa** [comment]
Try passing your to the datepicker using the options property `[options]="{}"`

``` javascript
<div class="input-group" daterangepicker (selected)="selected($event, mainInput)" [options]="options">
```

**Comment by BenevidesLecontes** [comment]
@evansmwendwa it doesn't work as expected neither, it's applying the same settings for all components instances in the page. Did you tried to reproduce the issue? What i'm trying to do is to use my component like this, with slight different settings passed as inputs.
![image](https://cloud.githubusercontent.com/assets/1839361/26829639/a9c92e48-4a9c-11e7-96d8-16a0832111bd.png)
Ex: See this usage:
```
<div class="row">
        <div class="col-lg-4 col-sm-4 col-xs-4 col-md-4">
          <app-date-rangepicker [control]="searchFilterForm" [opens]="'right'" [itemName]="'periodo_criacao'" [id]="'periodo_criacao'"
                                [label]="'Período da criação da ocorrência'"></app-date-rangepicker>
        </div>
        <div class="col-lg-4 col-sm-4 col-xs-4 col-md-4">
          <app-date-rangepicker [control]="searchFilterForm" [opens]="'left'" [itemName]="'periodo_registro'" [id]="'periodo_registro'"
                                [label]="'Período de registro'"></app-date-rangepicker>
        </div>
        <div class="col-lg-4 col-sm-4 col-xs-4 col-md-4">
          <app-date-rangepicker [opens]="'center'" [control]="searchFilterForm" [itemName]="'periodo_prazo'" [id]="'periodo_prazo'"
                                [label]="'Período do prazo'"></app-date-rangepicker>
        </div>
        <div class="col-lg-4 col-sm-4 col-xs-4 col-md-4">
          <app-date-rangepicker (selectedDate)="teste($event)" [control]="searchFilterForm"
                                [itemName]="'periodo_encerramento'"
                                [opens]="'center'"
                                [id]="'periodo_encerramento'"
                                [label]="'Período de encerramento'"></app-date-rangepicker>
        </div>
      </div>
```

**Comment by evansmwendwa** [comment]
Kindly allow me sometime to create an example for you. I will be back online in a few hours. Hopefully I will get it to work with your sample

**Comment by evansmwendwa** [comment]
Your component is not monitoring any change detection, causing all the instances to be created using the default values and ignoring changes in the property binding.

To fix this implement `OnChanges` and then track the new values there so the datepicker get's updated every time the values change

``` typescript
import { Component, OnInit, OnChanges, OnDestroy, Input  } from '@angular/core';

// implement OnChanges
export class UiDateRangepickerComponent implements AfterViewInit, OnChanges {
  // your input properties
  @Input() id: string;
  @Input() itemName: string;
  @Input() label: string;
  @Input() control: FormGroup;

  // add config object
  public options: any = {};

  // bind all input to the config object here 
  // this should support change detection
 ngOnChanges() {
    this.options.opens = this.opens;
    this.options.drops = this.drops;
   // bind all the properties to the options object
   // NB: if you have many inputs consider using a single object and binding to it
  }
}
```

Then in your `ui-date-rangepicker.html` template bind `[options]` to your config object
**NB:** this is very important in order for the picker to see the different options
**NB:** since you are using multiple instances no need to use the global config `constructor(private daterangepickerOptions: DaterangepickerConfig)` unless just for skipping the bundled css

``` html
<div class="form-group">
  <label [attr.for]="id" [innerHtml]="label"></label>
  <div class="input-group" [options]="options" daterangepicker (selected)="selected($event, mainInput)" >
    <input [id]="id" [name]="id"
           [placeholder]="placeholder"
           [formControl]="control.get(itemName)"
           class="form-control uneditable-input input-layout"/>
    <a class="input-group-btn btn btn-icon btn-sm">
      <i class="glyphicon glyphicon-calendar"></i>
    </a>
  </div>
</div>
```

**Example** See this plunker for a simple example on the above

**Comment by BenevidesLecontes** [comment]
@evansmwendwa it's working fine, thanks for your help and your time.
