### ISSUE TITLE
Max year for single date picker dropdown

### ISSUE THREAD

**Issue by weiyangwan** [evansmwendwa/ng2-daterangepicker#26]
hi,

I am implementing a single date dropdown and programmatically set the date.

When I select the year dropdown, the max year given is 5 years from the programmatically set date.
For example, if I set a date as 15 June 1985, the max year that would appear is 1990. If I set a date as  15 Sep 1975, the max year that would appear is 1980. So if I want to select the year 2000 from there, it would be impossible from the dropdown.

Is there any way for me to custom the max year for the dropdown? Do apologise if I missed it in your documentations.

<img width="357" alt="dropdownpicker" src="https://user-images.githubusercontent.com/19562887/26865660-464b613e-4b90-11e7-8e5f-7ada5e5f73fe.png">

<img width="315" alt="dropdownpicker2" src="https://user-images.githubusercontent.com/19562887/26865898-583f56b0-4b91-11e7-87bc-57e304b64c77.png">

Thanks.

**Comment by evansmwendwa** [comment]
Which browser are you using? Can you try this in chrome and let me know you experience the same results.

**Comment by weiyangwan** [comment]
I'm using chrome

**Comment by evansmwendwa** [comment]
Can you share some code snippet we have a look at it. I am still not able to recreate your issue. Using Chrome for Windows 10

**Comment by weiyangwan** [comment]
*html:*

<div class="date-picker" daterangepicker [options]="options"
(selected)="selectedDate($event)">

*component:*

  options: any = {
    locale: { format: 'DD-MMM-YYYY' },
    alwaysShowCalendars: false,
  };

 selectedDate(value)

**Comment by weiyangwan** [comment]
i using chrome on macOS Sierra.

Anyway, may I confirm that you tried to recreate the issue but all were working fine?

html

'<div class="date-picker date-picker-single" daterangepicker [options]="options" (selected)="selectedDate($event)">'

component

  options = {
    locale: { format: 'YYYY-MM-DD' },
    singleDatePicker: true,
    showDropdowns: true,
  }

**Comment by evansmwendwa** [comment]
Try this demo and let me know if you are experiencing the same https://embed.plnkr.co/Q0la7
![dt](https://user-images.githubusercontent.com/3830832/27012140-f76921d2-4ed2-11e7-934b-23516e2197c2.jpg)
UcHsS5UxuOCDfZ5/

**Comment by weiyangwan** [comment]
Hi, if you look at your screenshot, the max year is 2022 as well, with initial value 2017.

Could you try to choose a date in an earlier year (say 2010), close the dropdown and open the dropdown again, is the max year now 2015?

i tried your plunker, it is still limiting to 05 years from initial value.

**Comment by evansmwendwa** [comment]
There's always a minimum displayed year and a maximum displayed year. In my case the number of years displayed in the range spans for 55 years. if you choose 2022, then the list will re-adjust from 1962 - 2027 and keep re-adjusting depending on the current selected year in order to fit in the list.

You can dictate where the ranges leans to by setting either minDate or maxDate

**Comment by weiyangwan** [comment]
Noted. Thanks for looking into this.
