### ISSUE TITLE
Show chosen date range label as text input value

### ISSUE THREAD

**Issue by arturikoX** [evansmwendwa/ng2-daterangepicker#27]
I have a project where we have daterangepicker with some predefined ranges like Today, Yesterday, This Week, and we found that in some cases it's better to see the chosen range as a label, not as actual date.
For example when choosing Today the input should have its label as a value:
![Image of datePicker](http://i.imgur.com/d1BTYTL.png)

Does it make sense to have such feature, so this behaviour will be handled by passing some configuration option?

Thank you.

**Comment by evansmwendwa** [comment]
This should be possible with change detection which I am working on currently. Will give it a test before release.

**Comment by arturikoX** [comment]
hi,
thank you for your response,
Do you have any estimated date of the new release ?

**Comment by evansmwendwa** [comment]
The selected event provides a label property together with the new selected date.

``` typescript
selectedDate(value: any, dateInput: any) {
  console.log(value);
  let label: string = value.label;
}
```
