### ISSUE TITLE
Two-way Data Binding with ngModal

### ISSUE THREAD

**Issue by lishichao1002** [evansmwendwa/ng2-daterangepicker#29]
Is there a two-way data binding with ngModal.

```
@Component({
    selector: 'my-app',
    template: `<input type="text" name="daterangeInput" [(ngModel)]="model" 
    />`,
})
export class AppComponent {

    public model: any = {};

}
```

**Comment by evansmwendwa** [comment]
At the moment the directive does not update inputs automatically. For that you have to tap to the `selected` event and update your model manually.

**Comment by lishichao1002** [comment]
Is there will support the feature in the next release. If not maybe I should fork your code and add the two-way data binding.

**Comment by evansmwendwa** [comment]
I am a bit busy at the moment. If you can do a fork for the feature please do and let me know if you need my help

**Comment by lishichao1002** [comment]
ok. Thanks a lot.
