### ISSUE TITLE
SystemJS

### ISSUE THREAD

**Issue by DanielBogdanBRT** [evansmwendwa/ng2-daterangepicker#3]
First off, great package! Super useful especially since other angular2 bootstrap implementations don't seem to have the date-range

I saw your note: 
"I have not tested usage with system js for now, currently working on Angular 2 Webpack setup, will update after thorough testing."

And wanted to report back my findings: your dependencies right now are a little rough around the edges, but overall this can be jammed into SystemJS with one exception (at least as far as our implementation seems to support): the css file you're including. The require statement in daterangepicker.component.ts for the css file is causing issues as our importer continues to try and flag it as a js file. There may be work arounds, but thats as far as I was able to get in the amount of time I dedicated to look into this. Do you have any suggestions/ways to implement without having the css required?

**Comment by evansmwendwa** [comment]
Thanks a lot for the feedback.

I have been working to clean up the package and I managed to release a patch with a couple of additional features and reduced the dependencies.

At the moment you should be able to skip adding the css by using the config service **See the updated documentation and try using the new release and let me know if it fixes your situation** 

I am testing on a SystemJS setup and I will update once I get things working properly.

**Comment by bitf09a013** [comment]
In my app.component.ts, I have set the SkipCss to false like

```
constructor(private daterangepickerOptions: DaterangepickerConfig) {
        this.daterangepickerOptions.skipCSS = true;
    }
```

But it still continues to give me this error as pointed out by Daniel above

![1](https://cloud.githubusercontent.com/assets/5657544/23787265/0c058ace-0593-11e7-83bd-379dd9ea927b.png)

**Comment by evansmwendwa** [comment]
I have made a new release `ng2-daterangepicker v2.0.2` that should now be working with SystemJS builds. Did a couple tests with Angular's Quickstart example, Webpack setup and Angular CLI setup and everything is now working.

Update and let me know if it works with your setups.

Also have a look at the updated instructions on how to setup in SystemJS.

**Comment by bitf09a013** [comment]
Perfect, it worked @evansmwendwa thank you
