### ISSUE TITLE
calendar does not show after choosing a custom button

### ISSUE THREAD

**Issue by jmls** [evansmwendwa/ng2-daterangepicker#30]
I have this html
```
<button md-raised-button color="primary" daterangepicker [options]="dateRangeOptions" (selected)="selectedDate($event)" *ngIf="!small">
                <md-icon>access_time</md-icon>
            </button>
```

where `dateRangeOptions` has a custom date ranges

```
this.dateRangeOptions.ranges = {
        'This Month': [thisMonth, moment(thisMonth).endOf('month')],
        'Last Month': [lastMonth, moment(lastMonth).endOf('month')],
        'Last 3 Months': [last3Months, moment(last3Months).add(3,'months').endOf('month')],
        'Last 6 Months': [last6Months, moment(last6Months).add(6,'months').endOf('month')],
        'Last 12 Months': [lastYear, moment(lastYear).endOf('year')]
      }
```
the first time I press the "date" button I get this 

![image](https://user-images.githubusercontent.com/929523/27540143-feb5445c-5a76-11e7-9bd5-84a7e5fb31c9.png)

If I choose any other button apart from the custom range buttons, then everything works just fine. However, if I choose the custom button, the date range is selected, but I now cannot choose the "date" button again. It just does a ripple and shows nothing else

**Comment by evansmwendwa** [comment]
The directive should work on any type of element where it's attached. Sometimes due to the location where the calendar code is added your page's css might be overriding the pickers css. If you can share some code in plunker I can try and replicate the issue so we have an idea why it's not working as expected.
