### ISSUE TITLE
Is there a way to use 'isInvalidDate'

### ISSUE THREAD

**Issue by TiGGeRTSK** [evansmwendwa/ng2-daterangepicker#31]
Hello there!
I would like to use "isInvalidDate", wondering if it is possible. And if so, could you please share some code examples how to disable date(s) (In addition to min-date and max-date options)

**Comment by evansmwendwa** [comment]
Ideally this should be possible. You can pass the function in the options object. I will share a sample later and also confirm port is in sync with the originals release version.

**Comment by evansmwendwa** [comment]
Pass isInvalidDate in your options. See example below and sample plunkr

https://jsfiddle.net/pvjLje2y/

```
public picker1 = {
        opens: 'left',
        startDate: moment().subtract(5, 'day'),
        endDate: moment(),
        isInvalidDate: function(date) {
          if (date.isSame('2017-09-26', 'day'))
            return 'mystyle';
          return false;
      	}
    }
```
