### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'input'

### ISSUE THREAD

**Issue by dipaktelangre** [evansmwendwa/ng2-daterangepicker#34]
I have been trying to get it working but has no luck. I have tried lot of example but none of them is working. Can  you please suggest how to get working. 
Below is the my component code 
```
import { Component, OnInit } from '@angular/core';
import { Daterangepicker } from 'ng2-daterangepicker';
import { DaterangepickerConfig } from 'ng2-daterangepicker';

declare var moment:any;
@Component({
  selector: 'date-range-picker',
  //templateUrl: './date-range-picker.component.html',
  template: `<input type="text" name="daterangeInput" daterangepicker [options]="options" (selected)="selectedDate($event)" />`,
  styleUrls: ['./date-range-picker.component.scss']
})
export class DateRangePickerComponent {
   public daterange: any = {};

    // see original project for full list of options
    // can also be setup using the config service to apply to multiple pickers
    public options: any = {
        locale: { format: 'YYYY-MM-DD' },
        alwaysShowCalendars: false,
    };

    public selectedDate(value: any) {
        this.daterange.start = value.start;
        this.daterange.end = value.end;
        this.daterange.label = value.label;
    }
}
```
 
Always getting below error. 
```
Uncaught Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'input'. ("<input type="text" name="daterangeInput" daterangepicker [ERROR ->][options]="options" 
```

**Comment by evansmwendwa** [comment]
Do you have this in your module?

```
import { Daterangepicker } from 'ng2-daterangepicker';

@NgModule({
    imports: [Daterangepicker]
})
```

Also are you using angularcli, webpack or systemjs?

**Comment by raviitsoft** [comment]
I am using angularcli. Please can you suggestion? how can use? I am getting same error

**Comment by raviitsoft** [comment]
compiler.js:485 Uncaught Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'div'. ("lass="calendar">
                    <div class="input-group" name="daterangeInput" daterangepicker [ERROR ->][options]="calendarOptions" (selected)="selectedDate($event)" (applyDaterangepicker)="applyDate($even"): ng:///SubscribersAndEarningsModule/ApmComponent.html@54:83

**Comment by dipaktelangre** [comment]
@raviitsoft  ```import { FormsModule } from '@angular/forms';```  import ```FormsModule``` in your module which will fix issue.

**Comment by dipaktelangre** [comment]
```import { FormsModule } from '@angular/forms';```
```@NgModule({
    imports: [FormsModule]
})```

**Comment by mherried** [comment]
I had the same issue here. It was solved by importing the Module in the component you are using.  I originally had it imported in a Shared Module.. this did not work.  After i put this in the Module i was using it worked.   Also the FormsModule has to be imported before this module.

**Comment by VikashChoudahry** [comment]
I had faced the same issue. And I was able to resolve by following below steps:

1. Import the **Daterangepicker** from **ng2-daterangepicker** into respective module.
    For e.g. `import { Daterangepicker } from 'ng2-daterangepicker';`
2. Register **Daterangepicker** module into @NgModule
    `
   @NgModule({
    imports: [
        CommonModule,
        RouterModule.forChild(routes),
        ReactiveFormsModule,
        Daterangepicker
    ],
    ...
  ]
})`

Hope it helps!
