### ISSUE TITLE
Custom range selecting more than two monts

### ISSUE THREAD

**Issue by Geowan** [evansmwendwa/ng2-daterangepicker#38]
In the custom range how can one select a range of more than two months

Eg: between jan1 and may 30.

I have implemented it as in this [plunker](https://embed.plnkr.co/94HAl4q2ITLnahjhYOY0/l)

**Comment by evansmwendwa** [comment]
You should be able to navigate the months and select any range by clicking on the 'chevron' arrows. See image below.

If you are unable to see the icons try adding custom icons with css. Currently icons are only supported via bootstrap 3 or font-awesome

<img width="672" alt="screen shot 2017-08-20 at 11 26 16 pm" src="https://user-images.githubusercontent.com/3830832/29498164-058887ea-85ff-11e7-968e-a45e5f8d6c5d.png">
