### ISSUE TITLE
Overriding styles does not work

### ISSUE THREAD

**Issue by penniath** [evansmwendwa/ng2-daterangepicker#39]
Hi,

I am trying to customize the styles of the date range picker in my main CSS file.
However, the generic styles are injected **after** the styles contained in the main.css.

This is my .angular-cli.json configuration:
```
"styles": [
    "assets/css/main.css"
],
```
Any suggestions?

Thanks,

Fernando

**Comment by evansmwendwa** [comment]
Set skipCSS to true in the DaterangepickerConfig service. This should be done in the first component that will use the datepicker.

```
constructor(private daterangepickerOptions: DaterangepickerConfig) {
   this.daterangepickerOptions.skipCSS = true;
}
```

**Comment by penniath** [comment]
Thank you @evansmwendwa!

That works great, is there a way to do it globally, though?

**Comment by evansmwendwa** [comment]
The service should set it up globally. You only need to do it once
