### ISSUE TITLE
Display daterangepicker on page load without clicking on input or calender button

### ISSUE THREAD

**Issue by mitulgohil** [evansmwendwa/ng2-daterangepicker#40]
Hi,
I want to display date range picker with page load without clicking on input or calendar icon. I am unable to find any option for it.

**Comment by evansmwendwa** [comment]
The daterangepicker does not have that option

**Comment by mitulgohil** [comment]
Is there any plan to add these feature.?

**Comment by evansmwendwa** [comment]
Not at the moment but any pull request implementing the feature would be acceptable.

This angular module is a port of the original Bootstrap Date Range picker and currently supports just the features available in the original jQuery plugin. It's basically a wrapper of that plugin. 

http://www.daterangepicker.com/
