### ISSUE TITLE
Depend on moment-mini instead of moment?

### ISSUE THREAD

**Issue by cyberabis** [evansmwendwa/ng2-daterangepicker#41]
Can we make this library light-weight by using [moment-mini](https://github.com/ksloan/moment-mini) or [date-fns](https://github.com/date-fns/date-fns) instead of moment? Since currently tree-shaking is not fully effective for moment module, the build get's bloated up. Related discussion - https://github.com/moment/moment/issues/2373.

**Comment by evansmwendwa** [comment]
Sounds good. I will runs some tests to see how it performs and then we can have it in the next release

**Comment by cyberabis** [comment]
Thanks!
