### ISSUE TITLE
How to change calendar icon?

### ISSUE THREAD

**Issue by 02harleen** [evansmwendwa/ng2-daterangepicker#44]
Change date range calendar icon on input field?

**Comment by evansmwendwa** [comment]
Which input? the one on the datepicker can be customized using css

**Comment by 02harleen** [comment]
If the calendar is open, so display two input field with the calendar icon. So how to change it?

**Comment by evansmwendwa** [comment]
The calendar uses these classes which you can override with css `fa fa-calendar glyphicon glyphicon-calendar`
