### ISSUE TITLE
Get the date format in another component but does not pik the date format.

### ISSUE THREAD

**Issue by 02harleen** [evansmwendwa/ng2-daterangepicker#45]
```
@Input() dateFormat : any = "MM-DD-YYYY";
public options: any = {
      locale: { format: this.dateFormat }
 };
```

In another component is:-
`<RangeFilter dateFormat="DD/MM/YYYY"></RangeFilter>`

Does not pick up the dateFormat="DD/MM/YYYY". It is pickUp the default set dateFormat.

Please tell us how to solve this problem.

**Comment by evansmwendwa** [comment]
In Angular your string must be quoted before passing it to a property

```
<RangeFilter dateFormat="'DD/MM/YYYY'"></RangeFilter>
```

**Comment by 02harleen** [comment]
This is not working.

**Comment by evansmwendwa** [comment]
That's because by the time the value from the @Input() is updated the options object will have already been created. Have a look at Angular Change Detection on ways to fix that
