### ISSUE TITLE
How can I disable the daterangepicker?

### ISSUE THREAD

**Issue by ViktorPlohl** [evansmwendwa/ng2-daterangepicker#47]
My user interface contains fields that need to be disabled conditionally. How can I disable the daterange picker? (ex.: https://getbootstrap.com/docs/4.0/components/forms/#disabled-forms)

**Comment by evansmwendwa** [comment]
You can disable pointer events with css
```
pointer-events: none;
```

**Comment by ViktorPlohl** [comment]
It works, thank you.
