### ISSUE TITLE
Only show placeholder in date picker and after select date, date will display.

### ISSUE THREAD

**Issue by lakhvir1994** [evansmwendwa/ng2-daterangepicker#49]
Hi, I have does not enter start date but default show current date.  I have use single date picker. Now my requirement is:- 
Show input filed with placeholder. After click on input filed date calendar will be open then select any date so show in input field. 
Please tell us how is it possible. 
My options is:- 
`this.dateOptions = {
         locale: { format: "MM/DD/YYYY" },
         singleDatePicker: true
      };`

**Comment by evansmwendwa** [comment]
You can use `[(ngModel)]` to bind a variable to your input. The datepicker actually doesn't care about your input and can be attached to any html element. How you choose to update your input or even whether to use an input is your choice.

See an example on usage https://embed.plnkr.co/94HAl4q2ITLnahjhYOY0/ 

If that doesn't work for you modify the plunker and share so we can work on it
