### ISSUE TITLE
Set initial date value

### ISSUE THREAD

**Issue by priyaponni** [evansmwendwa/ng2-daterangepicker#5]
Hi,

I need to show the daterangepicker with one of the options selected by default. Can you please let me know how this can be achieved? I see only one '@Input' for options in your component. I really need to set the initial value, otherwise need to  create custom. Please let me know.

Thanks.

**Comment by evansmwendwa** [comment]
You can pass in `startDate` and `endDate` in the options object

```
<input  daterangepicker [options]="{startDate:'2017/01/02', endDate:'2017/01/20' }" >
```

Note that if you want the dates displayed in say inputs value you will need to bind to a variable using ngModel.

See this link for a list of all available options http://www.daterangepicker.com/#options

**Comment by priyaponni** [comment]
Doesn't seem to work when I give both ranges, start & endDates in the options of a datepicker.
`this.dateUpdatedOptions = { ranges: {
              'Today': [moment(), moment()],
              'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
              'Last 7 Days': [moment().subtract(6, 'days'), moment()],
              'Last 30 Days': [moment().subtract(29, 'days'), moment()],
              'This Month': [moment().startOf('month'), moment().endOf('month')],
              'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
          startDate : moment().subtract(1, 'days'),
          endDate : moment().subtract(1, 'days') 
        };`

Something like this doesn't set the initial value.

**Comment by evansmwendwa** [comment]
Please provide a full sample of your usage (with both ts and html template file is separate) or provide a link to a git repo.

**Comment by VijetaH** [comment]
@priyaponni were you able to solve this ?? How to set both dates ??

**Comment by evansmwendwa** [comment]
@VijetaH What are you trying to achieve I see if I can help?

**Comment by VijetaH** [comment]
I am not able to set default dates using this : 
private dateoptions = {
  endDate: 1517461200000,
  startDate: 1496289600000
};

**Comment by evansmwendwa** [comment]
You can't simply pass a number to the properties. The property expects a valid date object or date string matching the passed locale. You can try and use moment.js to parse your timestamps to dates
