### ISSUE TITLE
$(...).daterangepicker is not a function

### ISSUE THREAD

**Issue by f3l1xss** [evansmwendwa/ng2-daterangepicker#50]
Hi there,

I encountered that exception when I attempted to use ng2-daterangepicker at my webpack project.
I noticed this might be because ng2-daterangepicker is having its own jquery Dependency
and my project having my own jquery. This problem doesn't seem to exist when building using
System Js from your example.
 
Do you have any idea how to make the datepicker use the same jquery as what the project is using? Perhaps changing Jquery as PeerDependency will help?

Thanks a lot

**Comment by evansmwendwa** [comment]
Are you using Webpack within Angular CLI? Also can you provide some sample code of your implementation.

**Comment by f3l1xss** [comment]
Hi,

I do not use Angular CLI, what I have is a normal webpack Project which has jquery dependency,
I have this in my webpack config:

`plugins: [
	  // Needed for Jquery Global Variable Initialization

 new webpack.ProvidePlugin({
		  'jQuery': 'jquery',
	      '$': 'jquery',
	      'jquery': 'jquery',
	      'windows.jQuery': 'jquery',
	      'Popper': 'popper.js/dist/umd/popper.min.js'
	    }), `

which basically is telling webpack to replace '$' in my project with import from 'jquery package'.

The problem now is that inside ng2-daterangepicker project you also have dependency of Jquery. This will result in project ending up having 2 versions of jquery and $.fn.daterangepicker defined in the inner jquery instead of the one used by my project.
I am also new at webpack so my understanding might not be completely correct.

You can also take a look here : 
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1662#issuecomment-254492046

I think they are also experiencing the same issue.

I tried forking the master branch and changing the jquery and its type defintion to peerDependencies instead of dependencies and now there seem to be no issue, not sure though if there is a drawbacks in doing that.

Thanks

**Comment by evansmwendwa** [comment]
Okay, Will look into it but later

**Comment by idl-asad** [comment]
@evansmwendwa any updates on this issue ? I am getting same error on angular-cli.

**Comment by eduinredes** [comment]
Hi, @idl-asad me too.

**Comment by atul121001** [comment]
i am getting too with the angular-cli

**Comment by f3l1xss** [comment]
Hi,

You can try my package 
https://www.npmjs.com/package/ng2-daterangepickers

It basically contains the exact same thing. I just set Jquery as peer dependency .

**Comment by evansmwendwa** [comment]
Publishing an update shortly

**Comment by evansmwendwa** [comment]
v2.0.11 moved the dependencies to peerDependencies.

Please test and let me know if it fixes the issue

**Comment by atul121001** [comment]
Now Its giving error 
Cannot find module './lib/daterangepicker/daterangepicker.module'.
ERROR in /home/atul/workspace/acquisition-ui/node_modules/ng2-daterangepicker/index.d.ts (2,15): Cannot find module './lib/daterangepicker/daterangepicker.component'.
ERROR in /home/atul/workspace/acquisition-ui/node_modules/ng2-daterangepicker/index.d.ts (3,15): Cannot find module './lib/daterangepicker/config.service'.

**Comment by evansmwendwa** [comment]
My bad. Did a rushed release.

Please try v2.0.12 and revert

**Comment by evansmwendwa** [comment]
@atul121001 @f3l1xss @eduinredes is this issue fully fixed?

**Comment by kitloong** [comment]
Hi,

For those who have similar issue with webpack, adding this into webpack config works for me

```
resolve: {
    alias: {
        'jquery': path.join(__dirname, 'node_modules/jquery/dist/jquery'),
    }
}
```

Credited from https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1319#issuecomment-208339466

**Comment by genru** [comment]
@evansmwendwa this issue still exists.

i use angular-cli with `"ng2-daterangepicker": "^2.0.12"`  get same error `$(...).daterangepicker is not a function`

html
```
                <div class="input-group" daterangepicker [options]="{startDate:dateInput.start, endDate:dateInput.end }" (selected)="selectedDate($event, dateInput)" >
                    <span class="form-control uneditable-input"  name="daterange" >
                        {{ dateInput.start | date:'M/dd/y' }} - {{ dateInput.end| date:'M/dd/y' }}
                    </span>
                    <span class="input-group-btn">
                        <a type="button" class="btn btn-default"><i class="glyphicon glyphicon-calendar"></i></a>
                    </span>
                </div>
```

app.module.ts
```
@NgModule({
    ....
       inports: [ 
          ....
          Daterangepicker]
```

did i miss anything?

**Comment by genru** [comment]
@kitloong please how to apply this in a angular-cli project?

**Comment by evansmwendwa** [comment]
@kitloong do you have jQuery installed in your project?

**Comment by genru** [comment]
Hi, everyone,

the latest news is that when I downgrade my jquery lib to 2.3 from 3.x, then update jquery back to 3.x. this issue got disappeared. I am not expert of angular, but I believe this is a dependency issue.

if anybody meet this problem, please try to install ng-daterangepicker before jquery(any version), let package management choose right dependency lib for you.

hope this helps

**Comment by kitloong** [comment]
@genru Glad you have solved your issue.

@evansmwendwa Yes i do have jQuery installed, however it still complain about this error. 

```
var webpack = require("webpack");

    ...

    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery"
        })
    ]
```

**Comment by greatsayan** [comment]
Hi, 

I have an issue with you bootstrap-daterangepicker version. How can I override the version used in your package with mine? I want to use the latest one which is 3.0.3 and not 2.1.30.

I'm using webpack too.

Thanks
