### ISSUE TITLE
Browser issues

### ISSUE THREAD

**Issue by surajmdr2003** [evansmwendwa/ng2-daterangepicker#51]
daterangepicker is  not working on safari mac
https://embed.plnkr.co/94HAl4q2ITLnahjhYOY0/

**Comment by evansmwendwa** [comment]
What version of Safari are you using? I have tested on Safari 10.1.2 and it's working okay. There's a known issue with Angular Date pipes on some versions of safari though.

**Comment by surajmdr2003** [comment]
Thanks for quick response, i have tested on Version 9.1.2 (11601.7.7), i think it's date pipes issues. if so, then, is there any solution to solved.

**Comment by evansmwendwa** [comment]
Check if using a polyfill solves the issue

https://github.com/angular/universal/issues/516
