### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'input'

### ISSUE THREAD

**Issue by XimenaWang** [evansmwendwa/ng2-daterangepicker#53]
compiler.es5.js:1694 Uncaught Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'input'. ("ass="form-group">
			<input type="text" class="form-control" name="daterangeInput" daterangepicker [ERROR ->][options]="options" (selected)="datesSelected($event)" />
		</div>
	</form>
"): ng:///AppModule/DateRangePickerComponent.html@4:81

**Comment by evansmwendwa** [comment]
Make sure you have this in your module 

```typescript
import { Daterangepicker } from 'ng2-daterangepicker';

@NgModule({
    imports: [Daterangepicker]
})
```
