### ISSUE TITLE
Demo not working on IE11

### ISSUE THREAD

**Issue by knottydon** [evansmwendwa/ng2-daterangepicker#54]
I’m looking for an Angular 2+ control for date range picker.  I tried your control in all browsers but I’m having a problem on IE 11.  Here’s a screenshot when I try to run it on IE11:
![22](https://user-images.githubusercontent.com/2860498/31156462-1666bc2a-a8e7-11e7-8e9d-ca795906c539.png)
 
And here’s how it looks like on IE11:
![23](https://user-images.githubusercontent.com/2860498/31156482-40308a04-a8e7-11e7-87b3-a1ec345beda1.jpg)

Please help.  Thanks!

**Comment by evansmwendwa** [comment]
If you want to support IE11 you have to enable the necessary pollyfills

https://angular.io/guide/browser-support

**Comment by knottydon** [comment]
Thank you for your reply.

 

Have a nice day,

Don
