### ISSUE TITLE
How to add a placeholder to ng2-daterangepicker single date component

### ISSUE THREAD

**Issue by razorhenry1** [evansmwendwa/ng2-daterangepicker#55]
First of all , thank you for adding this beautiful component. Please help me in adding a placeholder to single date picker component

**Comment by evansmwendwa** [comment]
use normal html placeholder attribute

**Comment by fadelguy** [comment]
normal placeholder attribute not working...

**Comment by evansmwendwa** [comment]
where are you using the placeholder? the directive doesn't modify any attributes, in fact it doesn't care whether you attach it to an input or any other html element.

If you share some code i can be able to assist you.

**Comment by fadelguy** [comment]
<input type="text" placeholder="test" class="form-control" daterangepicker [options]="options" (selected)="selectedDate($event, daterange)"/>

instead my placeholder i see the date range of today:
11.10.2017- 11.10.2017

**Comment by razorhenry1** [comment]
The example shown to use this component at https://embed.plnkr.co/94HAl4q2ITLnahjhYOY0/ uses a span , hence placeholder attribute is not working. I changed it to input and now its working fine.
There is one more issue. If one uses a placeholder, then one cannot select today's day as its already selected. 

For workaround , I am using the onapply action but its an additional overhead.

**Comment by evansmwendwa** [comment]
The placeholder has nothing to do with the selected dates in the picker.

If you don't provide a range in your options then the picker will have today's date selected as the start and end date. In the picker, there's always a range selected.

The picker itself does not get any values from the input attached to it unless you program a logic to update it depending on the input's value. If you look at my example above you notice the picker wasn't even attached to an input but a span and a button and it still worked.

Also an html placeholder is not a value and so there's no way it's going to affect the values selected in the picker.

**Comment by evansmwendwa** [comment]
@fadelguy in your example

```
<input type="text" placeholder="test" class="form-control" daterangepicker [options]="options" (selected)="selectedDate($event, daterange)"/>
```
There's no way the picker will modify the displayed value here has your input doesn't have ngModel directive

**Comment by razorhenry1** [comment]
@evansmwendwa In case of single date picker , it's an issue , if we are using a placeholder . Single date picker selects today's date by default. Hence onselect function doesn't work it I try to select today's date.

**Comment by razorhenry1** [comment]
@fadelguy  use ngModel. I have separated into ngModel and ngModelChange in order to use a date pipe :
 <input type="text"  class="form-control"  placeholder="Choose Date"  daterangepicker 
  [options]="options" (selected)="selectedDate($event, daterange)" 
  [ngModel]="dateInput.start | date: 'MM/dd/y' " (ngModelChange)="dateInput.start=$event" />

**Comment by evansmwendwa** [comment]
@razorhenry1 @fadelguy I think i have understood the issue at hand, correct me if am wrong.

Im assuming you want to display an input where users can select a date but have it start without a default value hence end up displaying a the input placeholder until the user selects a value.

Since the picker always has a date selected and will attempt to automatically bind to to the attached control if it detects one (this can be disabled in your options)

I suggest approaching it like this.

* Wrap the input with a div then attache the datepicker directive to that div - that way if users click anywhere in the div they will select a date and your input control can display the placeholder until a user selects a date.

See below example:

```html
<div class="input-group" daterangepicker [options]="singlePicker" (selected)="singleSelect($event)">
    <input name="tDate" placeholder="Choose Date" type="text" class="form-control" [(ngModel)]="singleDate">
</div>
```
Updating the input ngModel after user selects a date

```typescript
private singleSelect(value: any) {
    this.singleDate = value.start;
}
```

**Comment by razorhenry1** [comment]
@evansmwendwa You got it right. I have created issue at : https://plnkr.co/edit/S0bcjqc0RyglUp9GIRPh?p=preview

**Comment by evansmwendwa** [comment]
Is the issue sorted now? The placeholder is displaying in the code sample

**Comment by razorhenry1** [comment]
@evansmwendwa Please try to select today's date. Its an issue.

**Comment by evansmwendwa** [comment]
The datepicker automatically selects todays date by default if no startdate is passed in the options. You will not be able to select it because it's already selected.

**Comment by fadelguy** [comment]
@evansmwendwa  after your solution, 
i can see the placeholder 
but when i choose range dates, in the input i see [object, object] instead the range 'date-date'

**Comment by evansmwendwa** [comment]
The picker returns an object.

You console log the object or cast it to json {{ value | json }} to see the available properties
