### ISSUE TITLE
How to set value to formcontrol using ReactiveFormsModule if clean data in datebox 

### ISSUE THREAD

**Issue by thanhxuanhd** [evansmwendwa/ng2-daterangepicker#57]
I have control fromDate using ReactiveFormsModule 

```html
<label>From Date <span class="text-danger">*</span></label>
                <input class="form-control" formControlName="fromDate" type="text" daterangepicker
                       (selected)="fromDateChange($event)" [options]="dateOptions" name="fromDate">
                <span class="text-danger"
                      [hidden]="addEditForm.controls.fromDate.valid || addEditForm.controls.fromDate.pristine"
                      translate>
                         From Date required
</span>
```

Option control
```typescript
public dateOptions: any = {
    locale: {format: "DD/MM/YYYY"},
    alwaysShowCalendars: false,
    singleDatePicker: true
  };
```

Component
```typescript
public addEditForm: FormGroup = new FormGroup({
    fromDate: new FormControl(null, Validators.required)
});
```

Event change
```typescript
fromDateChange(event) {
    if (event.start) {
      this.addEditForm.controls["fromDate"].setValue(
        event.start
      );
}
```
But I clean data  and out focus value set is today  but Event change fromDateChange not run and set data to form. Result value not set form not save. I try event cancelDaterangepicker or hide hideDaterangepicker

**Comment by evansmwendwa** [comment]
`patchValue` and `setValue` should work

See this example: https://embed.plnkr.co/Ynz0TEoqEydFZ4zVcZdw/

```typescript
import { FormControl } from '@angular/forms';

declare var moment:any;

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class App {
    public travelDate = new FormControl();
    
    private updateDate(value: any) {
        this.travelDate.patchValue(moment(value.start).format('LL') + ' - ' + moment(value.end).format('LL'));
    }
}
```

```html
<div class="form-group" style="padding:20px;">
  <div daterangepicker [options]="singlePicker" (selected)="updateDate($event)">
    <input placeholder="Choose Travel Dates" class="form-control" [formControl]="travelDate">
  </div>
</div>
```

**Comment by thanhxuanhd** [comment]
Sorry I try with patchValue and setValue should but not work. Data set value is default  today. If i clean by backspace not run function set (selected) set data

**Comment by evansmwendwa** [comment]
It works in the example i shared. Maybe if you can share your code I can assist you.

Also the event will only be fired after clicking on the picker and not when the input is edited.

**Comment by thanhxuanhd** [comment]
My code
I have from group
`<form novalidate [formGroup]="addEditForm" (ngSubmit)="onSave($event)">

    <div class="form-group">
       <label>From Date <span class="text-danger">*</span></label>
                <input class="form-control" formControlName="fromDate" type="text" daterangepicker
                       (selected)="fromDateChange($event)" [options]="dateOptions" name="fromDate">
                <span class="text-danger"
                      [hidden]="addEditForm.controls.fromDate.valid || addEditForm.controls.fromDate.pristine"
                      translate>
                         From Date required
  </span>

<button (click)="onSave($event)" class="btn btn-info btn-with-icon mr-right-10"
                                        type="submit" [disabled]="!addEditForm.valid"
                                        translate>
                                    <i class="fa fa-floppy-o"></i> Lưu
                                </button>
   </div>
</form>`
Component 
`public addEditForm: FormGroup = new FormGroup({
    fromDate: new FormControl(null, Validators.required)
`});`

Event selected 
`fromDateChange(event) {
    if (event.start) {
      this.addEditForm.controls["fromDate"].setValue(
        event.start
      );
}`
Option 
`public dateOptions: any = {
    locale: {format: "DD/MM/YYYY"},
    alwaysShowCalendars: false,
    singleDatePicker: true
  };`

Default value set model set from date = toDay();
If i clean by backspace not run function set (selected) set data Form Group control valid button save is disabled. Button control show date set default  but  this.addEditForm.controls["fromDate"] value is null

**Comment by thanhxuanhd** [comment]
@evansmwendwa 
Issue fix with config html
```
<div daterangepicker [options]="singlePicker" (selected)="updateDate($event)">
    <input placeholder="Choose Travel Dates" class="form-control" [formControl]="travelDate">
 </div>
```
But not work config 
```
<input class="form-control" formControlName="fromDate" type="text" daterangepicker
                       (selected)="fromDateChange($event)" [options]="dateOptions" name="fromDate">
```
Thank for example shared

**Comment by evansmwendwa** [comment]
Can you share your code in plunker or github I try and help you with the debugging

**Comment by thanhxuanhd** [comment]
You see my example 
https://plnkr.co/edit/p7lw7khPGOa3dJmezGNN?p=preview
Input controlDate2 init is null but show to day value. I selected date and clearn data. Input controlDate2 not clean. But controlDate1 work

**Comment by evansmwendwa** [comment]
In your first example the picker is attached to the containing div while in the second one the picker is attached to the input itself.

When the picker is attached to an html input element it will auto update the input automatically. Considering there's always a selected range in the picker then the attached element will always have a value.

You can disable that by setting `autoUpdateInput` to `false` in your picker options

```
 autoUpdateInput: false
```

```typescript
public singlePicker: any = {
      "autoUpdateInput": false,
      locale: { format: "DD/MM/YYYY" },
      alwaysShowCalendars: false,
      singleDatePicker: true
    };
```
