### ISSUE TITLE
Ranges show up twice

### ISSUE THREAD

**Issue by lohiarahul** [evansmwendwa/ng2-daterangepicker#58]
![image](https://user-images.githubusercontent.com/2647136/31799634-f65b727a-b586-11e7-8cc0-440e5c56e09a.png)

Using 
"ng2-daterangepicker": "^2.0.10",
"jquery": "^3.2.1",

with Angular CLI

**Comment by evansmwendwa** [comment]
No idea why that would happen. Did you get it fixed?

**Comment by lohiarahul** [comment]
@evansmwendwa  Yes. The parent tag defaulted to `<body>` and in my application, the body tag appeared twice, once inside the other due to some other erroneous code. This error revealed a bigger error for me. Nevertheless, I think this could be fixed in the library. The `prepend` function causes this behaviour, should check if duplicate parents are found and operate only on one of them or flag warning/error.
