### ISSUE TITLE
ES6 Build Issue with angular/cli

### ISSUE THREAD

**Issue by jafferabbas** [evansmwendwa/ng2-daterangepicker#6]
The uglify-js bundled with webpack breaks when doing a production build with daterangepicker as it does not work with es6. 

Is there an es5 version? If not what the best way around it?

The exact build error is:

ERROR in vendor.3171750698bdd8016e8a.bundle.js from UglifyJs
Unexpected token: name (DaterangepickerConfig) [vendor.3171750698bdd8016e8a.bundle.js:67402,6]

Thanks.

**Comment by evansmwendwa** [comment]
Please update to the latest version v2.0.3 I have switched the build target to es5. Should work with uglifyjs on webpack setups.

**Comment by jafferabbas** [comment]
Thanks so much. Saved my the headache of ng eject and uglifyjs
