### ISSUE TITLE
Year Dropdownlist range

### ISSUE THREAD

**Issue by amrut123456789** [evansmwendwa/ng2-daterangepicker#60]
How to show years from 1957 to 2017 in year dropdown list

**Comment by evansmwendwa** [comment]
You can set `minDate` and `maxDate` in the options. The list displayed has a limit but if you select a very early year it will update again to load more earlier years

**Comment by amrut123456789** [comment]
Yeah sir. But i want to extend that limit range

**Comment by evansmwendwa** [comment]
Check out the original picker http://www.daterangepicker.com/

We are only porting it to Angular so if you find a way in the documentation it should work in Angular as well
