### ISSUE TITLE
Error with version 2.0.11

### ISSUE THREAD

**Issue by penniath** [evansmwendwa/ng2-daterangepicker#61]
Hi,

After installing last version (2.0.11), the error below is thrown on prod building.
It seems like the package is not correctly built.

> ERROR in Error: Unexpected value 'Daterangepicker in .../node_modules/ng2-daterangepicker/index.d.ts' imported by the module 'SharedModule

Regards,

Fernando

**Comment by evansmwendwa** [comment]
Please try v2.0.12 and revert. v2.0.11 is broken

**Comment by penniath** [comment]
Hi @evansmwendwa,

Updated and checked. It works smoothly again.
Thanks!
