### ISSUE TITLE
calendar icon

### ISSUE THREAD

**Issue by HEHEMonster** [evansmwendwa/ng2-daterangepicker#62]
![image](https://user-images.githubusercontent.com/16699173/32476260-1de333f4-c3b1-11e7-95f9-e134d3e68071.png)
![image](https://user-images.githubusercontent.com/16699173/32476288-42cc8814-c3b1-11e7-9687-a183cd55e2b5.png)
Can you tell me how can i to replace this calendar icon in code ? i'm using bootstrap4 now ,thanks!

**Comment by evansmwendwa** [comment]
You can override the calendar icon using global css by styling the .fa-calendar class. Either css background or content

**Comment by HEHEMonster** [comment]
OK,i did it, thaks you very much
