### ISSUE TITLE
parentEl is working?

### ISSUE THREAD

**Issue by hellsm83** [evansmwendwa/ng2-daterangepicker#69]
i've tried to add parentEl in my configuration, but it seems that the daterangepicker is added in body and not near the parent i gave him...

**Comment by hellsm83** [comment]
nevermind, i've solved the issue

**Comment by SmileBin** [comment]
How did you solve it? picker popup is float on my screen. it seems that picker is added in body not my components

**Comment by antonpegov** [comment]
It works if you add it to config object.
