### ISSUE TITLE
same as #69 ( parentEl? )

### ISSUE THREAD

**Issue by SmileBin** [evansmwendwa/ng2-daterangepicker#70]
After wrote daterangepicker in my components, but datepickerrange components(<div>tags) is outside of app-root (it's in 1st level of body tag) not in my component tags. it causes scroll problem. after open picker, then scroll it, picker components are not sticked to input tags.

**Comment by SmileBin** [comment]
using angular v5.0

**Comment by evansmwendwa** [comment]
The attaching is done using jQuery which is pa harps the reason using a parentEL sometimes fails to work as expected.

I will do some more experimentation to see how we can have that fixed but I can't action to it urgently.

As per the scroll issue when the component is in body, I haven't experienced it and I can assist you to fix that.

**Comment by SmileBin** [comment]
I put parentEl  property as my content-body tag in DaterangepickerConfig. Solved it.
