### ISSUE TITLE
How to remove border arrow?

### ISSUE THREAD

**Issue by antonpegov** [evansmwendwa/ng2-daterangepicker#71]
Is there simple way to remove arrow from border? I don't want to move all css, like you say in doc. Just remove the arrow: http://joxi.ru/52anqL6CGq5VQA

**Comment by evansmwendwa** [comment]
I think you can override this with global css. The picker is placed directly to the body element

**Comment by antonpegov** [comment]
I used 

> .daterangepicker
>     &:before, &:after
>       display: none !important;
