### ISSUE TITLE
Somehow, this component is killing NgbModal component.

### ISSUE THREAD

**Issue by Zerokk** [evansmwendwa/ng2-daterangepicker#73]
Hi there,

Though this component works fine, it seems to be breaking another component you can find in NPM, and not _an unpopular one_, precisely. It's one NgBootstrap modal component:
 https://ng-bootstrap.github.io/#/components/modal/examples

Basically, when I use ng2-daterangepicker and put the directive into the DOM, I can't select checkboxes that are dynamically loaded into the modal. But if I comment all the datepicker template implementation, and just load the component class... it works fine. 

So somehow, this directive implementation is breaking something. 

Do you have any idea on what it can be? I've been quick checking the code and I find nothing... and that's bad because I need to fix this up quite quickly. And _happy_ thing is that both components (yours and the other) are requirements in this project 😅😅😅 so... Can you help me with this issue?

Thank you so much and sorry!

EDIT: I don't get absolutely any errors here, it's just silent bug. When I select one of those checks, they just don't get checked.

**Comment by Zerokk** [comment]
Something I just "discovered" is that it's some problem when binding one function to the (click) action in my checkbox. The function it aims to, doesn't trigger. Weird.

**Comment by Zerokk** [comment]
I'll leave here the template code, in case it's useful for you:

```
  <!-- Modal -->
  <ng-template #content let-c="close" let-d="dismiss">
    <div class="modal-header">
      <h4 class="modal-title">Dimensions</h4>
      <button type="button" class="close" aria-label="Close" (click)="d('Cross click')">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
     
    <div class="modal-body modal-text col-md-12">
        <fieldset *ngFor="let attribute of listAttributes(config.attributes.available)" >
            <div *ngIf="!config.attributes.fixed[attribute.label]">
            <div class="form-group">
              <label class="control-label col-lg-4">
                {{attribute.label}}
              </label>
              <div class="col-lg-8 inputs">
                <label *ngFor="let value of attribute.values; let i = index" class="{{config.attributes.type[attribute.key]}}">
                  <input
                    [type]="config.attributes.type[attribute.key]"
                    (click)="toggle_selected(attribute.key, attribute.values[i])"        <-- Here is the problem!
                    [checked]="is_selected(attribute.key, attribute.values[i])"            
                    *ngIf="is_defined(attribute.values[i])"
                  >
                  {{ value }}
                </label>
              </div>
            </div>
           </div>
        </fieldset>
      
          <div class="row-fluid clearfix col-md-12">
              Selected dimension filter(s):
          </div>
          <div id="selectedDimensions" class="row-fluid clearfix col-md-12">
           <span *ngFor="let attribute of listAttributes(config.attributes.selected)">
              <span *ngIf="attribute.values.length>0 && !config.attributes.hidden[attribute.key]">
               <span class="tag label label-info">
                 {{attribute.label}}:
                 {{attribute.values}}
               </span>
              </span>
           </span>
         </div>
         </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-success" (click)="save();c()">Save</button>        
      <button type="button" class="btn btn-outline-dark" (click)="c('Close click')">Close</button>
    </div>

  </ng-template>
```

**Comment by Zerokk** [comment]
New info: When jquery is loaded at line 6 of your file daterangerpicker.component.js, it breaks my other component. When I comment this line, the other component starts working, but of course, the datepicker stops working. I'm seeing what I can do to fix it.

**Comment by Zerokk** [comment]
So how could this be fixed?

**Comment by evansmwendwa** [comment]
Not sure. But the daterangepicker is dependent on jQuery.

I will try experimenting further to see whether it can work but I don't have a lot of time at my disposal.
