### ISSUE TITLE
template driven form validator

### ISSUE THREAD

**Issue by jegger06** [evansmwendwa/ng2-daterangepicker#74]
Hello, I am trying to use your plugin in an angular 5 environment and I have not figure out on how to validate this via template driven. I want this to be detected by the form that I currently have but it seems it is not working for me. Can you help me figure this one out? Thanks.

**Comment by evansmwendwa** [comment]
Is your picker attached directly to the input? The picker does not modify the form elements in any way (it just bind to the native click event) so form validation should work normally.

In case the dirty events don't trigger because the input did not get focus you should be able to trigger the input touched events manually.

**Comment by jegger06** [comment]
The input says invalid and touched even if I have already selected the dates.

Here is my code below:

`<div class="form-group">
    <label for="daterange">Task Date</label>
    <input type="text" [(ngModel)]="daterangeInput" (change)="daterangeInput" class="form-control" name="daterangeInput" daterangepicker [options]="options" (selected)="selectedDate($event, daterange)" #daterangeInputField="ngModel" required>

    <div *ngIf="daterangeInputField.invalid && (daterangeInputField.dirty || daterangeInputField.touched)">
      <div *ngIf="daterangeInputField.errors.required">
        Task Date is required
      </div>
    </div>
  </div>`

can you figure out what's wrong?

**Comment by alex88** [comment]
@evansmwendwa did you fix it somewhere? I'm having the same issue, the input says it's invalid because I set the `required` attribute but I'm getting the same error even if I have a date selected
