### ISSUE TITLE
ng build --prod fail with aot

### ISSUE THREAD

**Issue by aholbreich** [evansmwendwa/ng2-daterangepicker#75]
I have one issue with timepicker

```
ng build --prod
Date: 2017-12-08T13:47:22.061Z                                                       
Hash: aad176391b7d2d8fe523
Time: 10654ms
chunk {0} styles.eb535cf3f14c8ad47bb5.bundle.css (styles) 161 kB [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.d00ea6ec004e1622a93a.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in src/app/messagesearch/timerangepanel/timerangepanel.component.html(6,113): : Property 'options' does not exist on type 'TimerangepanelComponent'.
```

while time picker component looks like this

```
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { DaterangepickerConfig } from 'ng2-daterangepicker';
import * as moment from 'moment';
...
export class TimerangepanelComponent implements OnInit {
  public daterange: any = {};
  private endOfToday = moment.utc().endOf('day');

  constructor(private daterangepickerOptions: DaterangepickerConfig) {
    this.daterangepickerOptions.settings = {
      locale: { format: 'DD.MM.YYYY HH:mm' },
      alwaysShowCalendars: false,
      timePicker: true,
      timePicker24Hour: true,

      ranges: {
        'Today': [moment.utc().startOf('day'), this.endOfToday],
        'Yesterday': [moment.utc().subtract(1, 'day').startOf('day'), moment.utc().subtract(1, 'day').endOf('day')]],
      }
    };
  }

  ngOnInit() {
  }
```

However `ng serve `,  `ng build` working, but bg build --prod is only working while aot is disabled.
```
ng build --prod --aot false
```

Can you point me to the solution here?
P.S. I'm relative new to angular and javaScript/typeScript.

P.S.S.
```
<fieldset>
  <legend class="legend-class">Time range</legend>
  <div class="row">
    <div class="col-md-7">
      <div class="form-group">
        <input id="rangepicker" class="form-control input-sm" type="text" name="daterangeInput" daterangepicker [options]="options"
          (selected)="selectedDate($event, daterange)" />

      </div>
    </div>
    
  </div>

</fieldset>
```

**Comment by evansmwendwa** [comment]
The package supports aot compilation. The error you are getting is due to undeclared property options. It would be helpful to see where your picker is attached. Please share your template code too

**Comment by aholbreich** [comment]
Sure... 
```
<fieldset>
  <legend class="legend-class">Time range</legend>
  <div class="row">
    <div class="col-md-7">
      <div class="form-group">
        <input id="rangepicker" class="form-control input-sm" type="text" name="daterangeInput" daterangepicker [options]="options"
          (selected)="selectedDate($event, daterange)" />

      </div>
    </div>
    
  </div>

</fieldset>
```

**Comment by aholbreich** [comment]
Lokes like AOT works again when i remove 
`[options]="options`

since i use
` constructor(private daterangepickerOptions: DaterangepickerConfig)`
it looks like i don't need options member...

**Comment by Jelencro** [comment]
I have similar problem when building with AOT... I declare datePickerOptions on ngOnInit() and it looks like this: `        this.daterangepickerOptions.settings = {
            locale: {
                format: 'DD.MM.YYYY',
                separator: " ...",
                applyLabel: "...",
                cancelLabel: "...",
                fromLabel: "...",
                toLabel: "...",
                customRangeLabel: "...",
                weekLabel: "...",
                daysOfWeek: ["...","...","...","...","...","...","..."],
                monthNames: ["...","...",...],
                firstDay: 1
            },
            alwaysShowCalendars: false,
            ranges: {
                '...': [Date.now(), Date.now()],
                '...': [this.subtractDate(1, 'days'), this.subtractDate(1, 'days')],
                '...': [this.subtractDate(7, 'days'), Date.now()],
                '...': [this.subtractDate(1, 'months'), Date.now()],
                '...': [this.subtractDate(3, 'months'), Date.now()],
                '...': [this.subtractDate(6, 'months'), Date.now()],
            }
        };`
On building with AOT I get this error:
`ERROR in : "let-" is only supported on ng-template elements. ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" [ERROR ->]let-rowz="$implicit" let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].sec")
: "let-" is only supported on ng-template elements. ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" let-rowz="$implicit" [ERROR ->]let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6].sec")`
Any advice?

**Comment by evansmwendwa** [comment]
I am investigating this issue

**Comment by AmirSasson** [comment]
@evansmwendwa @Jelencro 
Use ngx-bootstrap@2.0.0-rc.0
it solved my problem

**Comment by Jelencro** [comment]
@AmirSasson it works for me as well. Thank you!

**Comment by evansmwendwa** [comment]
Has anyone found a good solution to this issue?
