### ISSUE TITLE
Ranges and apply

### ISSUE THREAD

**Issue by templth** [evansmwendwa/ng2-daterangepicker#76]
Hello,

I successfully implemented ranges with ng2-datarangepicker. They are correctly displayed and when I click on them, the range is selected. I would like to change a bit the behavior and not close the range picker dialog when clicking on a range but only display the range on the picker. The ranger dialog would be closed when clicking on the "apply" button... Is something possible using configuration only?

Thanks very much for your answer!

**Comment by evansmwendwa** [comment]
We don't have that feature but just in case check the link below for a complete list of available options.

http://www.daterangepicker.com/

**Comment by templth** [comment]
@evansmwendwa thanks very much for your answer!
