### ISSUE TITLE
Using daterangepicker without bootstrap

### ISSUE THREAD

**Issue by maxi7587** [evansmwendwa/ng2-daterangepicker#78]
Hi Evan,

I'm working on Angular 5 with Material Design and would prefer to avoid using bootstrap, but when i remove the bootstrap css the datepicker doesn't behave as expected... Any suggestions?

Thanks!

**Comment by evansmwendwa** [comment]
The picker is a port of the popular bootstrap daterangepicker and currently we haven't added any extra features apart from making it work seamless in Angular.

I will look into removing the jquery and bootstrap dependencies but there's no set timeline at the moment.
