### ISSUE TITLE
autoApply not working with Bootstrap 4

### ISSUE THREAD

**Issue by norchina** [evansmwendwa/ng2-daterangepicker#79]
Hi there! I have a very simple, yet annoying issue. I'm using Bootstrap 4 in my app and if I use the option `autoApply:true` it is still showing Apply button. I've tried it in the Plunker provided here as a demo (just changed Bootstrap version to 4.0.0-beta.3), and result is the same.

**Comment by evansmwendwa** [comment]
You can fix this by adding a global css style

```css
.applyBtn.hide {
    display: none;
}
```
