### ISSUE TITLE
Dropdown in Custom Range

### ISSUE THREAD

**Issue by Kalpesh300** [evansmwendwa/ng2-daterangepicker#80]
I am using this in my Angular 2 project.
In actual date-range-picker which is available on http://www.daterangepicker.com/, there is no dropdown for months and year in custom range selection. But in this project it is showing dropdowns for months and years.

**Comment by evansmwendwa** [comment]
You can use `showDropdowns: false`

**Comment by Kalpesh300** [comment]
It's working. Thanks

**Comment by Kalpesh300** [comment]
I have one more question. I am using different ranges like, today,tomorrow, this month etc. Can I set this month as default selected?

**Comment by evansmwendwa** [comment]
You can set this month as the default selected by setting the startDate and endDate options to be the same as the start and end of the default preset.
