### ISSUE TITLE
How to pick single start date and end date must be current date?

### ISSUE THREAD

**Issue by maniyalraj** [evansmwendwa/ng2-daterangepicker#81]
Is it possible to implement "Custom-to-Today" feature? 

While selecting, if the label is "Custom-to-Today", user must be able to select only one date and second date must automatically selected as Toady.

**Comment by evansmwendwa** [comment]
Not sure, please have a look at the documentation here http://www.daterangepicker.com/ you might find a way to do it with the provided methods
