### ISSUE TITLE
How to get custom range date in UTC format?

### ISSUE THREAD

**Issue by abariklrn** [evansmwendwa/ng2-daterangepicker#82]
I have to fetch records from different different zone, right now I am getting different records in different location.
for other date I am able to convert it in UTC with 

> moment.utc()

 method, but for custom date I am getting value in event and if I am doing 
```
value.start=moment(value.start).utc();
value.end=moment(value.start).utc();
```

still not getting the proper result

**Comment by evansmwendwa** [comment]
Did you find a solution to this? You should be able to convert your times with the moment library, the picker doesn't do any internal conversations
