### ISSUE TITLE
Not updating startDate and endDate

### ISSUE THREAD

**Issue by Kalpesh300** [evansmwendwa/ng2-daterangepicker#84]
I have a method which updates startDate and endDate as below.
` clearFilters() {
    this.options.startDate = this.start ;
    this.options.endDate = this.end;
  }`

In my constructor : 
`constructor() {`
  `this.start = moment().startOf('month');`
`    this.end = moment().endOf('month');`
  `  this.options = {`
    `  locale: {`
     `   format: 'DD/MM/YYYY',`
      `  firstDay: 1`
`      },`
`      startDate: this.start,`
 `     endDate: this.end,`
  `    showDropdowns: false,`
 `     ranges: {`
 `       'Today': [moment(), moment()],`
  `      'Tomorrow': [moment().add(1, 'days'), moment().add(1, 'days')],`
  `      'Current Week': [moment(), moment().add(6, 'days')],`
  `      'Next Week': [moment().add(7, 'days'), moment().add(14, 'days')],`
  `      'Current Month': [moment().startOf('month'), moment().endOf('month')]`
  `    },`
 `  };`
`}`

I am trying to set startDate and endDate with clearFilters method as mentioned above. But it is not getting updated on my picker. I think it is not calling its callback funtion.

**Comment by evansmwendwa** [comment]
Updating the `startDate` or `endDate` options does not change the range after the selection has been done.

If you want to update the `startDate` and `endDate` programmatically you have to use the `setStartDate` and `setEndDate` methods of the picker.

See this section in the documentation for more details: https://github.com/evansmwendwa/ng2-daterangepicker#daterangepicker-methods
