### ISSUE TITLE
select date is not showing at edit time in ng2-daterangepicker

### ISSUE THREAD

**Issue by NikhilRadadiya** [evansmwendwa/ng2-daterangepicker#85]
```
public singlePicker = {
        singleDatePicker: true,
        autoUpdateInput: true,
        showDropdowns: true,
        autoApply: true,
        drops: 'down',
        locale: {
            format: 'DD MMM YYYY'
        }
}
```
```
<input class="form-control form-line" type="text" daterangepicker 
id="dob" [options]="singlePicker" 
[(ngModel)]="dob" name="dob" />
```

storing date in db as YYYY-MM-DD and at edit time formatting with moment with

this.dob= moment(this.dob).format(DD MMM YYYY);

It shows the correct date in the placeholder with above format but when I click on datepicker it shows current date as selected in datepicker. it should show date from db which is showing in placeholder.

**Comment by evansmwendwa** [comment]
Try also setting the date from db in the `startDate` option

**Comment by NikhilRadadiya** [comment]
I'm setting date from db to a user object which contains `dob` and I'm using it in `[(ngModel)]="dob"`. Is there a other way to do it?

**Comment by NikhilRadadiya** [comment]
@evansmwendwa  Okay, Got it, but what if I have multiple datepicker in a form. I have to create multiple object of options, Right? is there a other way?

**Comment by evansmwendwa** [comment]
something like this

this.dob = moment().subtract(10, 'months');

```typescript
this.dob = moment(); // your dob from the database

this.dobOptions = {
  startDate: this.dob, // reassign the dob to the startDate
  autoUpdateInput: true
}
```

If you have multiple inputs that you want to use you can import the `DaterangepickerConfig` service and initialize it with the common config

``` typescript
constructor(private daterangepickerOptions: DaterangepickerConfig) {
        this.daterangepickerOptions.settings = {
            locale: { format: 'YYYY-MM-DD' },
            alwaysShowCalendars: false
        };
    }
```

Then your inputs can only have the input specific options

You could do that in a loop or wrap the input in a self contained component thats adds a custom property for the DOB using `@Input()`.

The example https://embed.plnkr.co/94HAl4q2ITLnahjhYOY0/ uses a loop to configure the multiple inputs

**Comment by NikhilRadadiya** [comment]
@evansmwendwa Thanks, `startDate` worked for me.
