### ISSUE TITLE
Build Issue in Angular4 with AOT

### ISSUE THREAD

**Issue by kavinithiy** [evansmwendwa/ng2-daterangepicker#86]
We are trying to integrate ng2-daterangepicker lib in Angular4 project. In develop env it is working fine. But while taking build using rollup/tsc we are getting below error in command prompt. Not sure what am missing.

Using system.js in our project.

'DaterangepickerConfig' is not exported by 'node_modules\ng2-daterangepicker\lib \daterangepicker\config.service.js'

**Comment by evansmwendwa** [comment]
Please refer to issue #75
