### ISSUE TITLE
set date range programatically

### ISSUE THREAD

**Issue by dotob** [evansmwendwa/ng2-daterangepicker#9]
how is it done?

**Comment by evansmwendwa** [comment]
Update to v2.0.5 and see the updated usage docs https://github.com/evansmwendwa/ng2-daterangepicker#daterangepicker-methods

**Comment by dotob** [comment]
awesome thanks man!

**Comment by kundansharma7** [comment]
> Update to v2.0.5 and see the updated usage docs https://github.com/evansmwendwa/ng2-daterangepicker#daterangepicker-methods

Not working, following error occurs:

error TS2724: Module '"../../../../node_modules/ng2-daterangepicker/ng2-daterangepicker"' has no exported member 'DaterangePickerComponent'. Did you mean 'DaterangepickerComponent'?
