### ISSUE TITLE
Prod Package ERROR TypeError: a(...).daterangepicker is not a function

### ISSUE THREAD

**Issue by bhagath007** [evansmwendwa/ng2-daterangepicker#94]
Hi There,

In dev instance it is working fine. **But I am getting any error when its running in prod profile** 

ERROR TypeError: a(...).daterangepicker is not a function
    at DaterangePickerComponent.render (vendor.9e6fc9901ed7da2d8183.bundle.js:1)
    at DaterangePickerComponent.ngDoCheck (vendor.9e6fc9901ed7da2d8183.bundle.js:1)
    at checkAndUpdateDirectiveInline (vendor.9e6fc9901ed7da2d8183.bundle.js:1)
    at checkAndUpdateNodeInline (vendor.9e6fc9901ed7da2d8183.bundle.js:1)
    at checkAndUpdateNode (vendor.9e6fc9901ed7da2d8183.bundle.js:1)
    at prodCheckAndUpdateNode (vendor.9e6fc9901ed7da2d8183.bundle.js:1)
    at Object.updateDirectives (main.9e6fc9901ed7da2d8183.bundle.js:1)
    at Object.updateDirectives (vendor.9e6fc9901ed7da2d8183.bundle.js:1)
    at checkAndUpdateView (vendor.9e6fc9901ed7da2d8183.bundle.js:1)
    at callViewAction (vendor.9e6fc9901ed7da2d8183.bundle.js:1)

**Please anyone help me...**

My Package.json;
{
  "name": "test",
  "version": "0.0.0",
  "description": "Description for test",
  "private": true,
  "license": "UNLICENSED",
  "cacheDirectories": [
    "node_modules"
  ],
  "dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/cdk": "2.0.0-beta.10",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/material": "2.0.0-beta.10",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "@angular/router": "4.4.6",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.28",
    "@types/c3": "0.4.48",
    "angular2-moment": "1.7.0",
    "bootstrap": "4.0.0-alpha.6",
    "c3": "0.4.18",
    "chart.js": "2.7.1",
    "chartjs-plugin-datalabels": "^0.3.0",
    "core-js": "2.4.1",
    "font-awesome": "4.7.0",
    "hammerjs": "2.0.8",
    "jquery": "3.2.1",
    "jquery-ui-bundle": "1.12.1",
    "moment": "2.18.1",
    "ng2-daterangepicker": "^2.0.12",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.2",
    "swagger-ui": "2.2.10",
    "tether": "1.4.0",
    "zone.js": "0.8.13"
  },
  "devDependencies": {
    "@angular/cli": "1.2.0",
    "@angular/compiler-cli": "4.4.6",
    "@types/c3": "0.4.48",
    "@types/file-saver": "0.0.1",
    "@types/jasmine": "2.5.53",
    "@types/node": "8.0.13",
    "angular2-template-loader": "0.6.2",
    "awesome-typescript-loader": "3.2.1",
    "browser-sync": "2.18.12",
    "browser-sync-webpack-plugin": "1.2.0",
    "c3": "0.4.18",
    "codelyzer": "3.1.2",
    "copy-webpack-plugin": "4.0.1",
    "css-loader": "0.28.4",
    "exports-loader": "0.6.4",
    "extract-text-webpack-plugin": "3.0.0",
    "html-loader": "0.4.5",
    "html-webpack-plugin": "2.29.0",
    "jasmine-core": "2.6.4",
    "karma": "1.7.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage": "1.1.1",
    "karma-intl-shim": "1.0.3",
    "karma-jasmine": "1.1.0",
    "karma-junit-reporter": "1.2.0",
    "karma-notify-reporter": "1.0.1",
    "karma-phantomjs-launcher": "1.0.4",
    "karma-remap-istanbul": "0.6.0",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "2.0.4",
    "merge-jsons-webpack-plugin": "1.0.8",
    "ngc-webpack": "3.0.0",
    "node-sass": "4.5.3",
    "phantomjs-prebuilt": "2.1.14",
    "postcss-loader": "2.0.6",
    "proxy-middleware": "0.15.0",
    "rimraf": "2.6.1",
    "sass-loader": "6.0.6",
    "sourcemap-istanbul-instrumenter-loader": "0.2.0",
    "string-replace-webpack-plugin": "0.1.3",
    "style-loader": "0.18.2",
    "to-string-loader": "1.1.5",
    "tslint": "5.5.0",
    "tslint-loader": "3.5.3",
    "typescript": "2.4.1",
    "web-app-manifest-loader": "0.1.1",
    "webpack": "3.3.0",
    "webpack-dev-server": "2.5.1",
    "webpack-merge": "4.1.0",
    "webpack-notifier": "1.5.0",
    "webpack-visualizer-plugin": "0.1.11",
    "write-file-webpack-plugin": "4.1.0",
    "xml2js": "0.4.17"
  },
  "engines": {
    "node": ">=6.9.0"
  },
  "scripts": {
    "lint": "tslint --type-check --project './tsconfig.json' -e 'node_modules/**'",
    "lint:fix": "yarn run lint -- --fix",
    "ngc": "ngc -p tsconfig-aot.json",
    "cleanup": "rimraf target/{aot,www}",
    "clean-www": "rimraf target//www/app/{src,target/}",
    "start": "yarn run webpack:dev",
    "webpack:dev": "yarn run webpack-dev-server -- --config webpack/webpack.dev.js --progress --inline --hot --profile --port=9060",
    "webpack:build:main": "yarn run webpack -- --config webpack/webpack.dev.js --progress --profile",
    "webpack:build": "yarn run cleanup && yarn run webpack:build:main",
    "webpack:prod:main": "yarn run webpack -- --config webpack/webpack.prod.js --progress --profile",
    "webpack:prod": "yarn run cleanup && yarn run webpack:prod:main && yarn run clean-www",
    "webpack:test": "yarn run test",
    "webpack-dev-server": "node --max_old_space_size=8192 node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "webpack": "node --max_old_space_size=8192 node_modules/webpack/bin/webpack.js",
    "test": "karma start src/test/javascript/karma.conf.js",
    "test:watch": "yarn test -- --watch",
    "postinstall": "node node_modules/phantomjs-prebuilt/install.js"
  }
}

Thanks
Bhagath

**Comment by bhagath007** [comment]
Hi,

Any update on this?

**Comment by ollystephens1** [comment]
Installing jquery@3.3.1 fixes this.
