### ISSUE TITLE
There is not reset options to reset date or clear date

### ISSUE THREAD

**Issue by pramodrwt** [evansmwendwa/ng2-daterangepicker#95]

**Comment by evansmwendwa** [comment]
I believe you can implement that in your app

**Comment by pramodrwt** [comment]
I have change properties of `daterange` from typescript, but it's not reflecting on view
```

 this.daterange['start']= new Date().toISOString();
 this.daterange['end']= new Date().toISOString();
```

**Comment by mikecabana** [comment]
How may I ask you did this out of curiosity. Looking quickly would just set startDate and endDate to ''.

**Comment by mherried** [comment]
Example
@ViewChildren(DaterangePickerComponent) singledates: QueryList<DaterangePickerComponent>;
ngAfterViewInit() {
this.singledates.forEach((datepickerinstance) => datepickerinstance.datePicker.element.val(''));
}
