### ISSUE TITLE
Updating the position of daterangepicker when the input element is hidden

### ISSUE THREAD

**Issue by sagar2agrawal** [evansmwendwa/ng2-daterangepicker#98]
Because of some reasons I had to hide the input element due to which the daterangepicker is now opening at the top left of the browser, how to do i change it's position so it stays below a specific element only.

+ how to show only one calendar in daterangepicker when there's not enough space for two like in mobile devices.

**Comment by evansmwendwa** [comment]
Not sure for mobile. Though you can attach the picker to any visible div
