### ISSUE TITLE
bootstrap-daterangepicker should be a peer dependency

### ISSUE THREAD

**Issue by Ivan0xFF** [evansmwendwa/ng2-daterangepicker#99]
The version of bootstrap-daterangepicker being used in this project is quite old, but the project works just fine with new versions of bootstrap-daterangepicker.

Would it be possible to set it as a peer dependency and let us choose what version we'll use?

**Comment by evansmwendwa** [comment]
Thanks. Do you mind testing with the latest version and doing a pull request for this?

**Comment by greatsayan** [comment]
When I download the package, I still have bootstrap-daterangepicker in dependecies and not in peerDependencies...
My package.json:

`"dependencies": {
    "ng2-daterangepicker": "2.0.12",
    "bootstrap-daterangepicker": "3.0.3"
  }
`

**Comment by greatsayan** [comment]
Is it possible to publish your package on NPM repository?

npm view ng2-daterangepicker:

`
ng2-daterangepicker@2.0.12 | MIT | deps: 1 | versions: 18
Angular 2 DaterangePicker component
https://github.com/evansmwendwa/ng2-daterangepicker#readme

dist
.tarball https://registry.npmjs.org/ng2-daterangepicker/-/ng2-daterangepicker-2.0.12.tgz
.shasum: 9b0e58c37bc132246389298307ca7fa19f7de630
.integrity: sha512-Tcnd5CPGb5XkWLcD+5roagzKS4RL7QxpU7rT0GGtcduIC0jzj3tHRLO3VmkddbeivomSXkPnOlvBg2tjbYMI5A==

dependencies:
bootstrap-daterangepicker: ^2.1.25

maintainers:
- mevans <evansmwendwa@live.com>

dist-tags:
latest: 2.0.12

published 11 months ago by mevans <evansmwendwa@live.com>
`
